# Generated by Django 3.1.2 on 2021-03-12 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialCategory', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'managed': False, 'verbose_name_plural': 'material categories'},
        ),
    ]
