# Generated by Django 3.1.2 on 2021-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MaterialCategory', '0002_auto_20210312_1816'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='materialcategory',
            options={'managed': False, 'verbose_name': 'Material category', 'verbose_name_plural': 'Material categories'},
        ),
    ]
