# Generated by Django 3.1.2 on 2021-03-12 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('height', models.IntegerField(blank=True, db_column='Height', null=True)),
                ('chest_girth', models.IntegerField(blank=True, db_column='Chest girth', null=True)),
                ('chest_height', models.IntegerField(blank=True, db_column='Chest height', null=True)),
                ('waist_girth', models.IntegerField(blank=True, db_column='Waist girth', null=True)),
                ('hip_girth', models.IntegerField(blank=True, db_column='Hip girth', null=True)),
                ('neck_girth', models.IntegerField(blank=True, db_column='Neck girth', null=True)),
                ('shoulder_girth', models.IntegerField(blank=True, db_column='Shoulder girth', null=True)),
                ('hand_girth', models.IntegerField(blank=True, db_column='Hand girth', null=True)),
                ('hand_length', models.IntegerField(blank=True, db_column='Hand length', null=True)),
                ('back_width', models.IntegerField(blank=True, db_column='Back width', null=True)),
                ('length_waist_floor', models.IntegerField(blank=True, db_column='Length waist-floor', null=True)),
            ],
            options={
                'db_table': 'client',
                'managed': False,
            },
        ),
    ]
