# Generated by Django 3.1.2 on 2021-03-12 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False, 'verbose_name_plural': 'Clients'},
        ),
    ]
