# Generated by Django 3.1.2 on 2021-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0002_auto_20210312_1320'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'managed': False, 'verbose_name': 'Client', 'verbose_name_plural': 'Clients'},
        ),
    ]
