# Generated by Django 3.1.2 on 2021-03-15 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50, verbose_name='Name')),
                ('surname', models.CharField(db_column='Surname', max_length=255, verbose_name='Surname')),
                ('phone', models.CharField(db_column='Phone', max_length=255, verbose_name='Phone')),
                ('work_xp', models.IntegerField(blank=True, db_column='Work XP', null=True, verbose_name='Work XP')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
                'db_table': 'employee',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='EmployeeServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Employee services',
                'verbose_name_plural': 'Employee services',
                'db_table': 'employee services',
                'managed': False,
            },
        ),
    ]
