# Generated by Django 3.1.2 on 2021-03-12 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_column='Name', max_length=50)),
                ('surname', models.CharField(db_column='Surname', max_length=255)),
                ('phone', models.CharField(db_column='Phone', max_length=255)),
                ('work_xp', models.IntegerField(blank=True, db_column='Work XP', null=True, verbose_name='Work experience (years)')),
            ],
            options={
                'db_table': 'employee',
                'managed': False,
            },
        ),
    ]
