# Generated by Django 3.1.2 on 2021-03-12 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
        ('Employee', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IntermidiateModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_employee', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Employee.employee')),
                ('id_service', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='Service.service')),
            ],
        ),
    ]
