# Generated by Django 3.1.2 on 2021-03-12 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0002_intermidiatemodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'db_table': 'employee services',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='IntermidiateModel',
        ),
    ]
