# Generated by Django 3.1.2 on 2021-03-12 18:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0003_auto_20210312_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employeeservices',
            options={'managed': False, 'verbose_name_plural': 'Employee services'},
        ),
    ]
