# Generated by Django 3.1.2 on 2021-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Employee', '0004_auto_20210312_2119'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='employee',
            options={'managed': False, 'verbose_name': 'Employee', 'verbose_name_plural': 'Employees'},
        ),
        migrations.AlterModelOptions(
            name='employeeservices',
            options={'managed': False, 'verbose_name': 'Employee services', 'verbose_name_plural': 'Employee services'},
        ),
    ]
