# Generated by Django 3.1.2 on 2021-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
