# Generated by Django 3.1.2 on 2021-03-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0002_auto_20210313_1636'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'verbose_name_plural': 'Services'},
        ),
    ]
