# Generated by Django 3.1.2 on 2021-04-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Service', '0003_auto_20210324_1823'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='service',
            options={'managed': False, 'verbose_name': 'Service', 'verbose_name_plural': 'Services'},
        ),
    ]
