# Generated by Django 3.1.2 on 2021-03-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPrice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(blank=True, db_column='Price', decimal_places=2, max_digits=19, null=True, verbose_name='Price')),
                ('modification_date', models.DateTimeField(blank=True, db_column='Modification date', null=True, verbose_name='Modification date')),
            ],
            options={
                'db_table': 'material price',
                'managed': False,
            },
        ),
    ]
