# Generated by Django 3.1.2 on 2021-03-24 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fitting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index_number', models.IntegerField(blank=True, db_column='Index number', null=True, verbose_name='Index number')),
                ('date', models.DateTimeField(blank=True, db_column='Date', null=True, verbose_name='Date')),
                ('status', models.CharField(blank=True, db_column='Status', max_length=255, null=True, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Fitting',
                'verbose_name_plural': 'Fittings',
                'db_table': 'fitting',
                'managed': False,
            },
        ),
    ]
