# Generated by Django 3.1.2 on 2021-03-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ServicePrice', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceprice',
            options={'managed': False, 'verbose_name': 'Service price', 'verbose_name_plural': 'Services prices'},
        ),
    ]
