# Generated by Django 3.1.2 on 2021-03-12 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_ordermaterials'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderServices',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name_plural': 'order services',
                'db_table': 'order services',
                'managed': False,
            },
        ),
        migrations.AlterModelOptions(
            name='ordermaterials',
            options={'managed': False, 'verbose_name_plural': 'order materials'},
        ),
    ]
