# Generated by Django 3.1.2 on 2021-03-13 13:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0003_auto_20210312_2144'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'managed': False, 'verbose_name': 'Order', 'verbose_name_plural': 'Orders'},
        ),
        migrations.AlterModelOptions(
            name='ordermaterials',
            options={'managed': False, 'verbose_name_plural': 'Order materials'},
        ),
        migrations.AlterModelOptions(
            name='orderservices',
            options={'managed': False, 'verbose_name_plural': 'Order services'},
        ),
    ]
