# Generated by Django 3.1.2 on 2021-03-24 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_delete_orderservices'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ordermaterials',
            options={'managed': False, 'verbose_name': 'Order material', 'verbose_name_plural': 'Order materials'},
        ),
    ]
